"""Added price change tracking fields

Revision ID: 2a99e98fdd50
Revises: 
Create Date: 2025-11-21 09:13:40.791337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a99e98fdd50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_addition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_cost_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('old_selling_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('new_cost_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('new_selling_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_change_reason', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_addition', schema=None) as batch_op:
        batch_op.drop_column('price_change_reason')
        batch_op.drop_column('new_selling_price')
        batch_op.drop_column('new_cost_price')
        batch_op.drop_column('old_selling_price')
        batch_op.drop_column('old_cost_price')

    # ### end Alembic commands ###
